os: linux
dist: xenial

language: java
jdk: openjdk8

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
- sudo apt-get update
- sudo apt-get install -y libx11-dev libxpm-dev libxrandr-dev libpango1.0-dev devscripts
  debhelper fakeroot
- sudo ln -s /usr/lib/x86_64-linux-gnu/libX11.so /usr/lib/libX11.so
- sudo ln -s /usr/lib/x86_64-linux-gnu/libXpm.so /usr/lib/libXpm.so
- sudo ln -s /usr/lib/x86_64-linux-gnu/libXft.so /usr/lib/libXft.so
- sudo ln -s /usr/lib/x86_64-linux-gnu/libXrandr.so /usr/lib/libXrandr.so
- sudo ln -s /usr/lib/x86_64-linux-gnu/libpango-1.0.so /usr/lib/libpango-1.0.so
- sudo ln -s /usr/lib/x86_64-linux-gnu/libpangoxft-1.0.so /usr/lib/libpangoxft-1.0.so
- sudo ln -s /usr/lib/x86_64-linux-gnu/glib-2.0 /usr/lib/glib-2.0
- sudo ln -s /usr/lib/x86_64-linux-gnu/libgio-2.0.so /usr/lib/libgio-2.0.so
- sudo ln -s /usr/lib/x86_64-linux-gnu/libglib-2.0.so /usr/lib/libglib-2.0.so
- sudo ln -s /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so /usr/lib/libgmodule-2.0.so
- sudo ln -s /usr/lib/x86_64-linux-gnu/libgobject-2.0.so /usr/lib/libgobject-2.0.so
- sudo ln -s /usr/lib/x86_64-linux-gnu/libgthread-2.0.so /usr/lib/libgthread-2.0.so

before_deploy:
  - bash deploy.sh

deploy:
  provider: releases
  api_key:
    secure: cXKfAUxb2hpeKBPZFsc3lOV+fldQ8PhpJiOMnl+XWVjIMcQs71bE/CdoERqknRyekd0Bzb358M7kXwc1HgBfKc8kMhEQtEwrruhA8rTKcBDr+y4Yokl+xbcti1A2ocIG1hFhL9E7E2CAP2RVQy9sYqwiMCldRF31ZJPYEgXw9n4awFXBlNXTzpqhDJq72HJ8c8LK/Zi6Ol0wXArglhEjTw8UbbmJ3GVFxv558q2Viy+vv4uhwhrsXiNQuSaGW4DK7ZCyqETb9fgCnXWWKxoV3XNZ5QFOggnqQxs3zseKdRLQqJKUO0WL3milWF5fQtedxTujDW450n3xEklPPL5y1jYwrhNHRUEbmin9oRUAm3YdFr4NoNPnl5Pou9oHHkN7Ng4O9qzfmLp6rc5T9glCiCzlSsDVHwOvNWAEZNnQHMXD8ApjTw4UJicW0e/Zjlw8HVTqVZd5BvSs8BfyPRf7Pg/fH1A0q0JC3zW+bWLO1jwv+ndLcnXCiXXltRKbKyx8Yss2na5wm/xGB/6B65BHHiOOlaXApJqE6qADp4B6xHmRP8BmB8dJz/wEGOug/aOkv/7jzqolkzhDJP/ag6QT4V5dRMdptvR6GjXav2QIPdIWr28jK+vKWYLWz7RUHD7fO/SevtnAOAzL2RPavtJqd2Z4ZfoXjN/M1DX+l+Dl6pc=
  file_glob: true
  file: build/deb/deploy/*
  draft: true
  on:
    branch: master
#    tags: true
    repo: atennert/lcarswm
