language: java
jdk: openjdk8
notifications:
  email:
    on_success: never
    on_failure: always
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxcb1-dev libxcb-util-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libxcb.so /usr/lib/libxcb.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libxcb-util.so /usr/lib/libxcb-util.so