language: java

jdk: openjdk8

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libx11-dev libxpm-dev libxrandr-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libX11.so /usr/lib/libX11.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libXpm.so /usr/lib/libXpm.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libXrandr.so /usr/lib/libXrandr.so
